In this notebook we explore several ML approaches to classifying Alzheimer's disease (AD) and Parkinson's disease (PD) on the basis of vocal production features using the [Bridge2AI-Voice dataset](https://doi.org/10.13026/8xbn-nq66) 2.0.1 release. 

The high-level goal would be to develop a convenient and accessible assessment utility integrated into the existing proliferation of voice recording tools.

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
foreshadowing the methods we'll be trying: 
logistic regression, gradient boosting, svc, and mlp 
plus some attempts at dimensionality reduction
'''
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV, GroupKFold
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

#we use this to facilitate the mlp model selection
from itertools import combinations

#and this to make a tidier notebook
#import warnings
#warnings.filterwarnings(action="ignore",)

#I used numbergenerator.org to generate this number which will be my seed
rng = 48396

## load in and preprocess data

Described at length in their report, the Bridge2AI-Voice (B2AIv) dataset includes audio features derived from participant vocal production recordings; participant recruitment was initiated upon their presentation at "specialty clinics and institutions" and was based on membership in predetermined groups including "Neurological disorders", to which the AD and PD participants belong. 

Therefore, the data we're working with here are the audio derivative feature data ("static features.tsv") associated with AD, PD, and control participants (a subset of "phenotype.tsv"). 

NB: this work is all in the 2.0.1 data release, which is one release behind at time of writing.

In [43]:
#load in
pheno = pd.read_csv(r'bridge2ai-2.0.1/phenotype.tsv',sep='\t',header=0)
statics = pd.read_csv(r'bridge2ai-2.0.1/static_features.tsv',sep='\t',header=0)

#subset participants according to AD, PD, or control group
pd_pids = pheno[pheno['diagnosis_parkinsons_gsd_category_1_calculation']=='Yes'].participant_id.unique()
ad_pids = pheno[pheno['alz_dementia_mci']=='Checked'][['diagnosis_alz_dementia_mci_dt','participant_id']].dropna().participant_id.unique()
ct_pids = pheno[pheno['is_control_participant']=='Yes'].participant_id.unique()

In [47]:
#make sure we don't have overlap
sum(np.isin(pd_pids,ad_pids)),sum(np.isin(pd_pids,ct_pids)),sum(np.isin(ad_pids,ct_pids))

(0, 0, 0)

In [37]:
#how many participants do we have in each condition?
print(f'{len(np.unique(pd_pids))} PD participants \n{len(np.unique(ad_pids))} AD participants \n{len(np.unique(ct_pids))} Control participants')

31 PD participants
37 AD participants
64 Control participants

In [50]:
#subset static features from participants of interest
pd_stats = statics[statics['participant_id'].isin(pd_pids)]
ad_stats = statics[statics['participant_id'].isin(ad_pids)]
ct_stats = statics[statics['participant_id'].isin(ct_pids)]

'''
participants performed a variety of tasks for the B2AIv data.
to honor our high-level aim, we opt to use the most naturalistic one: free speech
we'll tidy up the data a bit and assign labels here too
'''
pd_fs = pd_stats[pd_stats['task_name'].isin(['Free-Speech','Free-speech-1','Free-speech-2','Free-speech-3'])][[i for i in pd_stats.columns if i not in ['session_id','task_name','transcription']]].dropna()
pd_fs['label'] = 1
ad_fs = ad_stats[ad_stats['task_name'].isin(['Free-Speech','Free-speech-1','Free-speech-2','Free-speech-3'])][[i for i in ad_stats.columns if i not in ['session_id','task_name','transcription']]].dropna()
ad_fs['label'] = 2
ct_fs = ct_stats[ct_stats['task_name'].isin(['Free-Speech','Free-speech-1','Free-speech-2','Free-speech-3'])][[i for i in ct_stats.columns if i not in ['session_id','task_name','transcription']]].dropna()
ct_fs['label'] = 0

In [57]:
'''
some participants contribute multiple data to the set, so we split
by participant to prevent leakage. We went with a 70/30 split 
to keep at least 10 diagnosis-bearing participants 
in the validation set for each diagnosis condition. 
'''

train_parts_pd = pd_fs.participant_id.unique()[:int(np.floor(len(pd_fs.participant_id.unique())*.7))]
train_data_pd = pd_fs[pd_fs['participant_id'].isin(train_parts_pd)]
val_data_pd = pd_fs[~pd_fs['participant_id'].isin(train_parts_pd)]

train_parts_ad = ad_fs.participant_id.unique()[:int(np.floor(len(ad_fs.participant_id.unique())*.7))]
train_data_ad = ad_fs[ad_fs['participant_id'].isin(train_parts_ad)]
val_data_ad = ad_fs[~ad_fs['participant_id'].isin(train_parts_ad)]

#for each disease condition we sample the same amount of control participants
#then combine their data with the patient data to form our final training and validation sets
ct_train_parts_pd = ct_fs.participant_id.drop_duplicates().sample(len(train_parts_pd),random_state=rng).values
train_data_pd = pd.concat([train_data_pd,ct_fs[ct_fs.participant_id.isin(ct_train_parts_pd)]])

ct_train_parts_ad = ct_fs.participant_id.drop_duplicates().sample(len(train_parts_ad),random_state=rng).values
train_data_ad = pd.concat([train_data_ad,ct_fs[ct_fs.participant_id.isin(ct_train_parts_ad)]])

ct_val_parts_pd = ct_fs[~ct_fs['participant_id'].isin(ct_train_parts_pd)].participant_id.drop_duplicates().sample(len(val_data_pd.participant_id.unique()),random_state=rng).values
val_data_pd = pd.concat([val_data_pd,ct_fs[ct_fs.participant_id.isin(ct_val_parts_pd)]])

ct_val_parts_ad = ct_fs[~ct_fs['participant_id'].isin(ct_train_parts_ad)].participant_id.drop_duplicates().sample(len(val_data_ad.participant_id.unique()),random_state=rng).values
val_data_ad = pd.concat([val_data_ad,ct_fs[ct_fs.participant_id.isin(ct_val_parts_ad)]])

In [65]:
#how much data do we have in each condition?
print(f"""
PD: {len(train_data_pd)} training samples & {len(val_data_pd)} validation samples 
AD: {len(train_data_ad)} training samples & {len(val_data_ad)} validation samples
""")

PD: 147 training samples & 75 validation samples
AD: 189 training samples & 93 validation samples

## ML benchmarking

Logistic regression, gradient boosting, support-vector machines, and neural networks are some common approaches to classification. PCA joins L1-penalized regression and ensemble selection methods as some common approaches to reducing the dimensionality of a predictor space to benefit the model of a classification problem. For these methods there also exists a considerable space of hyperparameters whose selection has consequence for the quality of the resulting model. We can't fully account for all of the possibilities in this work for practical reasons; rather, here we hope to survey some of the more-reasonable options.

In [49]:
pd_fs

,participant_id,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,...,local_shimmer,localDB_shimmer,apq3_shimmer,apq5_shimmer,apq11_shimmer,dda_shimmer,stoi,pesq,si_sdr,label
549,0581355f,23.116991,0.092754,21.342697,22.825933,24.566946,3.224249,225.074249,228.880539,32.518192,...,0.104231,1.006136,0.040367,0.057571,0.113731,0.121101,0.997695,3.452350,20.557886,1
550,0581355f,24.336529,0.113922,22.625807,23.774651,25.746820,3.121014,220.400818,196.087860,23.690027,...,0.103753,0.995240,0.042646,0.056899,0.101004,0.127937,0.994611,3.430656,20.712460,1
551,0581355f,27.139984,0.108037,24.597788,26.669912,29.847578,5.249790,150.989639,201.337662,29.131905,...,0.089274,0.879399,0.034279,0.046043,0.087223,0.102836,0.998030,3.640618,20.371683,1
970,0a282597,21.836462,0.041256,21.116489,21.717064,22.514534,1.398045,24.020990,10.231981,11.342595,...,0.099733,1.041104,0.031268,0.057010,0.128450,0.093804,0.983950,3.196664,19.711241,1
971,0a282597,22.335005,0.069886,21.427071,22.440836,23.452116,2.025045,175.395859,278.195953,17.169792,...,0.078371,0.783085,0.023630,0.038772,0.075018,0.070889,0.992179,3.646724,19.380545,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16857,df1453e7,25.831028,0.093940,23.968250,26.149540,27.952312,3.984062,107.598289,143.687622,35.949532,...,0.083193,0.855394,0.026366,0.042155,0.088318,0.079099,0.996015,3.829423,26.214901,1
16858,df1453e7,26.975775,0.112142,24.379810,26.953659,29.841303,5.461493,138.949738,175.578339,35.503948,...,0.097640,0.961507,0.035512,0.053817,0.103054,0.106535,0.998636,3.799230,23.188353,1
17997,eac8afdc,29.653240,0.094935,28.240120,29.455509,31.657101,3.416981,208.218246,212.480804,19.455433,...,0.111467,1.101201,0.046202,0.065270,0.111243,0.138607,0.985986,2.655652,19.009077,1
17998,eac8afdc,30.443380,0.067866,29.129333,30.194418,32.041504,2.912170,69.210289,106.138969,20.842350,...,0.119379,1.164370,0.052575,0.072507,0.120659,0.157726,0.965903,2.398106,17.836874,1
17999,eac8afdc,30.500942,0.076931,29.023972,30.072113,32.140091,3.116119,91.898209,143.206924,42.585533,...,0.119755,1.178021,0.052510,0.076137,0.120127,0.157531,0.962913,2.234024,15.233461,1

In [8]:
pd_stats[pd_stats['task_name'].isin(['Free-Speech','Free-speech-1'])]

,participant_id,session_id,task_name,transcription,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,...,ddp_jitter,local_shimmer,localDB_shimmer,apq3_shimmer,apq5_shimmer,apq11_shimmer,dda_shimmer,stoi,pesq,si_sdr
549,0581355f,21C1F1CA,Free-speech-1,NaN,23.116991,0.092754,21.342697,22.825933,24.566946,3.224249,...,0.030459,0.104231,1.006136,0.040367,0.057571,0.113731,0.121101,0.997695,3.452350,20.557886
970,0a282597,A6036FFA,Free-speech-1,To help patients get died died Diagnosis in th...,21.836462,0.041256,21.116489,21.717064,22.514534,1.398045,...,0.030252,0.099733,1.041104,0.031268,0.057010,0.128450,0.093804,0.983950,3.196664,19.711241
1254,0e3bbb6d,2CD1E0D6,Free-speech-1,All right. I'm interested in this study. My do...,31.424461,0.111820,31.076942,31.901854,32.999298,1.922356,...,0.034186,0.096911,0.954977,0.039595,0.049407,0.093868,0.118785,0.995881,3.324238,12.470948
1369,133372ef,BD54C6AC,Free-speech-1,NaN,26.253649,0.106699,24.143305,26.967258,28.319017,4.175713,...,0.035321,0.090628,0.940238,0.027054,0.044905,0.107312,0.081161,0.996596,3.519722,23.528757
1455,15443c3f,2F4F778F,Free-speech-1,I am interested in this study because it may h...,26.334810,0.243612,20.693600,27.649258,31.581661,10.888062,...,0.076247,0.162626,1.409223,0.075435,0.094270,0.131450,0.226305,0.948868,3.590131,24.354523
1639,16cce4e8,E88944CE,Free-speech-1,I am interested in this study because I have P...,33.155609,0.094500,32.414997,33.386608,34.512730,2.097733,...,0.028607,0.062906,0.705381,0.019396,0.028500,0.055283,0.058188,0.955044,2.620143,19.079657
1778,17578482,A8D26790,Free-speech-1,I'm interested in this study because I have Pa...,28.404694,0.096934,26.821936,28.278086,29.491602,2.669666,...,0.017054,0.099899,0.926064,0.043438,0.055102,0.087884,0.130315,0.924505,1.707437,19.631948
3126,27c3e7b2,49A6BFDB,Free-speech-1,NaN,25.442055,0.304191,13.605282,29.356421,30.902922,17.297640,...,0.022730,0.078382,0.805024,0.033299,0.039063,0.064356,0.099896,0.933973,1.888347,9.216987
3273,282b529e,84731907,Free-speech-1,I'm interested in this study for several reaso...,27.778841,0.068489,26.433769,27.679230,29.145910,2.712141,...,0.026038,0.080149,0.858649,0.022614,0.038007,0.080848,0.067841,0.990236,3.450804,25.828716
3519,2af5afbc,E7F3C75F,Free-speech-1,NaN,29.823526,0.069734,28.206337,29.622402,31.262657,3.056320,...,0.041592,0.124949,1.095971,0.057927,0.065555,0.097676,0.173780,0.998119,3.381133,17.890783
4083,301fcad0,4F01F3F9,Free-speech-1,I was interested in the study to give credence...,24.751797,0.072966,22.836391,24.981087,26.195961,3.359570,...,0.048209,0.173587,1.516841,0.080337,0.104657,0.222966,0.241012,0.956754,2.054378,13.808437
4678,3701dc59,F68CFBB9,Free-speech-1,I'm interested in this study because I'm havin...,31.616987,0.102993,29.815872,31.540266,34.124577,4.308704,...,0.030004,0.077865,0.794279,0.030333,0.037690,0.063180,0.090999,0.983505,2.710375,19.782055
5715,445c8cdf,0E616314,Free-speech-1,I am interested in this program because I have...,31.215403,0.077044,29.720421,31.076572,33.098534,3.378113,...,0.025801,0.084788,0.884895,0.032336,0.042245,0.079600,0.097007,0.897171,2.102609,14.751287
6722,55a3773a,CF2CDEBE,Free-speech-1,NaN,28.876535,0.056561,28.073288,29.036215,29.734011,1.660723,...,0.022768,0.078000,0.803878,0.027479,0.037831,0.074660,0.082436,0.992415,3.750173,27.426302
7506,62303614,6A211BFD,Free-speech-1,I'm interested in this study because I have a ...,34.357868,0.056303,33.118511,34.567806,35.666832,2.548321,...,0.030765,0.093035,0.963901,0.038481,0.051198,0.089721,0.115444,0.958921,2.674294,19.624264
8257,6afb0324,4FA5F552,Free-speech-1,NaN,30.145197,0.057054,29.093342,30.149040,31.340277,2.246935,...,0.014997,0.075206,0.932998,0.029018,0.039943,0.073067,0.087055,0.957450,1.978098,21.190063
8562,6e7c9c09,1708D604,Free-Speech,NaN,32.431076,0.132463,31.835249,33.187412,34.564766,2.729517,...,0.050281,0.116289,1.080824,0.043740,0.057444,0.104160,0.131221,0.985964,2.191777,10.265496
8563,6e7c9c09,1708D604,Free-speech-1,I'm interested in this study because it's a to...,31.451962,0.168183,29.902103,32.892044,34.640068,4.737965,...,0.054169,0.127221,1.198521,0.048454,0.064072,0.120754,0.145363,0.847537,1.390787,1.062093
9296,7869a54a,45B76D73,Free-speech-1,Why am I interested in this study? Because peo...,31.385393,0.108058,29.994152,31.235836,33.662792,3.668640,...,0.028958,0.083324,0.737010,0.030420,0.042541,0.081029,0.091260,0.990149,1.652039,-2.862064
9297,7869a54a,B9D3CA96,Free-speech-1,"Okay, why am I interested in this study? Why a...",29.338902,0.141652,29.328360,30.368086,31.648285,2.319925,...,0.040791,0.107562,1.041591,0.044620,0.060824,0.105947,0.133861,0.992447,2.355682,7.898406
9298,7869a54a,7EA3F87D,Free-speech-1,Why did I want to participate? I was diagnosed...,30.447567,0.091133,29.480017,30.320393,31.718958,2.238941,...,0.021979,0.071187,0.641986,0.024029,0.037324,0.071014,0.072087,0.992968,1.668799,-2.477181
9483,7ae91a65,B143DFB8,Free-speech-1,"I got diagnosed with Parkinson's, and I though...",26.065439,0.066193,24.803717,26.073761,27.340542,2.536825,...,0.027670,0.096628,0.891476,0.033215,0.051631,0.093916,0.099646,0.996777,3.438775,16.806198
9770,7de71fdd,C5E2AB8A,Free-speech-1,I'm interested in the study because I have Par...,23.061497,0.096140,21.608612,22.839264,24.369560,2.760948,...,0.024819,0.103638,0.977456,0.038540,0.056758,0.116928,0.115619,0.996995,3.861455,26.033815
10227,86b5a9e4,C87449CD,Free-speech-1,The reason why I'm interested in this study is...,19.844814,0.093397,18.447750,19.516378,20.811630,2.363880,...,0.076297,0.139963,1.237569,0.069019,0.077024,0.132720,0.207056,0.992775,3.273025,10.532589
10469,8b865a76,4E7BD33F,Free-speech-1,during the study on half of the future Parkins...,24.386950,0.179123,23.065235,25.225077,27.192844,4.127609,...,0.052347,0.114057,1.098553,0.051092,0.070060,0.102882,0.153277,0.756848,1.615894,6.871609
10700,8ddc9aec,BCD8AF09,Free-speech-1,"Yeah, so I'm interested in this study to help ...",23.577703,0.179736,21.589520,22.919058,24.774656,3.185137,...,0.026842,0.080627,0.802246,0.027830,0.044084,0.076282,0.083490,0.898770,2.036427,15.909205
10912,909d46d6,70D1F71C,Free-speech-1,"Well, I was at the doctor a couple days ago an...",29.079132,0.120154,27.052965,28.960917,30.549990,3.497025,...,0.023069,0.100223,0.943024,0.033466,0.058728,0.122731,0.100399,0.968719,2.593719,15.203964
11229,9937a44c,780C560C,Free-speech-1,I'm interested in this study because my speech...,21.909462,0.092762,20.150826,21.699358,23.598127,3.447302,...,0.038759,0.111209,1.062573,0.041642,0.062757,0.121479,0.124927,0.994488,2.850698,24.804155
13098,affb9760,22262304,Free-speech-1,I'm interested in the study because I am curio...,28.978083,0.113527,27.152473,28.453444,30.650646,3.498173,...,0.022492,0.093106,0.982384,0.038316,0.050032,0.084099,0.114948,0.895627,1.377861,-1.620605
13714,b7dfc6f4,16218870,Free-speech-1,NaN,29.800154,0.160820,27.096172,29.205116,32.156078,5.059906,...,0.032598,0.095867,0.914017,0.033952,0.049858,0.084546,0.101856,0.998576,3.770051,22.885403
14630,c2f5568b,C0507B39,Free-speech-1,He told me about it. It means a lot to me.,25.923641,0.072602,25.157402,25.829693,26.594301,1.436899,...,0.030782,0.126571,1.240077,0.058873,0.073150,0.124626,0.176619,0.880375,1.425281,1.985444
15945,d554cc1a,A27ADC59,Free-speech-1,I'm not interested in the study. I'm intereste...,30.366549,0.118802,28.900417,30.713692,32.739330,3.838913,...,0.033036,0.110195,1.069236,0.046331,0.059472,0.097077,0.138994,0.858100,1.376339,6.038157
15946,d554cc1a,9F930A08,Free-speech-1,NaN,31.057356,0.133620,28.980034,30.680006,33.288620,4.308586,...,0.031489,0.087440,0.893035,0.028753,0.042903,0.083084,0.086260,0.995062,3.051332,12.153110
15947,d554cc1a,99CFCE48,Free-speech-1,NaN,30.316177,0.106537,29.205477,30.282383,31.493391,2.287914,...,0.033811,0.107952,1.063936,0.033403,0.054420,0.111849,0.100209,0.989671,2.535416,1.615688
15948,d554cc1a,CB9852BA,Free-speech-1,"Well, I'm interested in this study because I h...",30.938618,0.102440,29.430222,30.898928,33.232830,3.802608,...,0.038093,0.116367,1.112947,0.037918,0.061917,0.129445,0.113754,0.986628,2.303637,2.025627
16856,df1453e7,6FF7DC14,Free-speech-1,I'm interested in this study because I have Pa...,26.490297,0.126792,23.924761,25.982147,29.040199,5.115438,...,0.029920,0.097761,0.951012,0.033841,0.051813,0.103108,0.101524,0.996671,3.968786,26.303339
17997,eac8afdc,56D4A4A6,Free-speech-1,I'm interested in this study in hoping to find...,29.653240,0.094935,28.240120,29.455509,31.657101,3.416981,...,0.025511,0.111467,1.101201,0.046202,0.065270,0.111243,0.138607,0.985986,2.655652,19.009077